export enum AffiliateErrorCode {
  // Application errors
  ALREADY_AFFILIATE          = "ALREADY_AFFILIATE",
  APPLICATION_PENDING        = "APPLICATION_PENDING",
  APPLICATION_REJECTED       = "APPLICATION_REJECTED",
  NOT_AN_AFFILIATE           = "NOT_AN_AFFILIATE",
  AFFILIATE_NOT_APPROVED     = "AFFILIATE_NOT_APPROVED",
  AFFILIATE_NOT_FOUND        = "AFFILIATE_NOT_FOUND",

  // Referral
  INVALID_REFERRAL_CODE      = "INVALID_REFERRAL_CODE",
  SELF_REFERRAL              = "SELF_REFERRAL",
  REFERRAL_CODE_TAKEN        = "REFERRAL_CODE_TAKEN",

  // Commission
  COMMISSION_NOT_FOUND       = "COMMISSION_NOT_FOUND",
  DOUBLE_COMMISSION          = "DOUBLE_COMMISSION",
  COMMISSION_ALREADY_PAID    = "COMMISSION_ALREADY_PAID",
  INELIGIBLE_FOR_COMMISSION  = "INELIGIBLE_FOR_COMMISSION",

  // Withdrawals
  INSUFFICIENT_BALANCE       = "INSUFFICIENT_BALANCE",
  PAYOUT_DETAILS_MISSING     = "PAYOUT_DETAILS_MISSING",
  WITHDRAWAL_NOT_FOUND       = "WITHDRAWAL_NOT_FOUND",
  WITHDRAWAL_ALREADY_PROCESSED = "WITHDRAWAL_ALREADY_PROCESSED",
  MINIMUM_WITHDRAWAL_NOT_MET = "MINIMUM_WITHDRAWAL_NOT_MET",

  // Rate limiting
  CLICK_RATE_LIMITED         = "CLICK_RATE_LIMITED",

  // Generic
  UNAUTHORIZED_ACCESS        = "UNAUTHORIZED_ACCESS",
  CONCURRENCY_CONFLICT       = "CONCURRENCY_CONFLICT",
}
