export enum NotificationErrorCode {
  INVALID_PUSH_TOKEN = "INVALID_PUSH_TOKEN",
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",
  BROADCAST_TARGET_NOT_FOUND = "BROADCAST_TARGET_NOT_FOUND",
  NO_RECIPIENTS = "NO_RECIPIENTS",
}
