export enum PaymentErrorCode {
  // Payment creation
  ORDER_NOT_FOUND             = "ORDER_NOT_FOUND",
  ORDER_NOT_PENDING           = "ORDER_NOT_PENDING",
  PAYMENT_ALREADY_EXISTS      = "PAYMENT_ALREADY_EXISTS",
  PAYMENT_ALREADY_SUCCEEDED   = "PAYMENT_ALREADY_SUCCEEDED",
  PAYMENT_NOT_FOUND           = "PAYMENT_NOT_FOUND",
  PAYMENT_MAX_ATTEMPTS        = "PAYMENT_MAX_ATTEMPTS",

  // Razorpay
  RAZORPAY_ORDER_CREATE_FAILED = "RAZORPAY_ORDER_CREATE_FAILED",
  INVALID_SIGNATURE            = "INVALID_SIGNATURE",
  RAZORPAY_ORDER_ID_MISMATCH   = "RAZORPAY_ORDER_ID_MISMATCH",
  AMOUNT_MISMATCH              = "AMOUNT_MISMATCH",

  // COD
  COD_NOT_AVAILABLE           = "COD_NOT_AVAILABLE",
  COD_ALREADY_SET             = "COD_ALREADY_SET",

  // Webhooks
  WEBHOOK_SIGNATURE_INVALID   = "WEBHOOK_SIGNATURE_INVALID",
  WEBHOOK_ALREADY_PROCESSED   = "WEBHOOK_ALREADY_PROCESSED",
  WEBHOOK_EVENT_MISSING       = "WEBHOOK_EVENT_MISSING",

  // Returns
  RETURN_ALREADY_REQUESTED    = "RETURN_ALREADY_REQUESTED",
  RETURN_NOT_ELIGIBLE         = "RETURN_NOT_ELIGIBLE",
  RETURN_NOT_FOUND            = "RETURN_NOT_FOUND",
  RETURN_ALREADY_RESOLVED     = "RETURN_ALREADY_RESOLVED",

  // Refunds
  REFUND_FAILED               = "REFUND_FAILED",
  REFUND_ALREADY_ISSUED       = "REFUND_ALREADY_ISSUED",
  PAYMENT_NOT_REFUNDABLE      = "PAYMENT_NOT_REFUNDABLE",

  // Shiprocket
  SHIPMENT_NOT_FOUND          = "SHIPMENT_NOT_FOUND",
  SHIPROCKET_AUTH_FAILED      = "SHIPROCKET_AUTH_FAILED",
  SHIPROCKET_ORDER_FAILED     = "SHIPROCKET_ORDER_FAILED",

  // Generic
  UNAUTHORIZED_ACCESS         = "UNAUTHORIZED_ACCESS",
  CONCURRENCY_CONFLICT        = "CONCURRENCY_CONFLICT",
}
