export enum PaymentErrorCode {
  // Payment creation
  ORDER_NOT_FOUND             = "ORDER_NOT_FOUND",
  ORDER_NOT_PENDING           = "ORDER_NOT_PENDING",
  PAYMENT_ALREADY_EXISTS      = "PAYMENT_ALREADY_EXISTS",
  PAYMENT_ALREADY_SUCCEEDED   = "PAYMENT_ALREADY_SUCCEEDED",
  PAYMENT_NOT_FOUND           = "PAYMENT_NOT_FOUND",
  PAYMENT_MAX_ATTEMPTS        = "PAYMENT_MAX_ATTEMPTS",

  // Razorpay
  RAZORPAY_ORDER_CREATE_FAILED = "RAZORPAY_ORDER_CREATE_FAILED",
  INVALID_SIGNATURE            = "INVALID_SIGNATURE",
  RAZORPAY_ORDER_ID_MISMATCH   = "RAZORPAY_ORDER_ID_MISMATCH",
  AMOUNT_MISMATCH              = "AMOUNT_MISMATCH",

  // COD
  COD_NOT_AVAILABLE           = "COD_NOT_AVAILABLE",
  COD_ALREADY_SET             = "COD_ALREADY_SET",

  // Local (non-courier) fulfilment
  ORDER_IS_MANUAL_FULFILMENT  = "ORDER_IS_MANUAL_FULFILMENT",
  SHIPMENT_ACTIVE             = "SHIPMENT_ACTIVE",

  // Webhooks
  WEBHOOK_SIGNATURE_INVALID   = "WEBHOOK_SIGNATURE_INVALID",
  WEBHOOK_ALREADY_PROCESSED   = "WEBHOOK_ALREADY_PROCESSED",
  WEBHOOK_EVENT_MISSING       = "WEBHOOK_EVENT_MISSING",

  // Returns
  RETURN_ALREADY_REQUESTED    = "RETURN_ALREADY_REQUESTED",
  RETURN_NOT_ELIGIBLE         = "RETURN_NOT_ELIGIBLE",
  RETURN_NOT_FOUND            = "RETURN_NOT_FOUND",
  RETURN_ALREADY_RESOLVED     = "RETURN_ALREADY_RESOLVED",

  // Refunds
  REFUND_FAILED               = "REFUND_FAILED",
  REFUND_ALREADY_ISSUED       = "REFUND_ALREADY_ISSUED",
  PAYMENT_NOT_REFUNDABLE      = "PAYMENT_NOT_REFUNDABLE",

  // Shipping (Delhivery)
  SHIPMENT_NOT_FOUND          = "SHIPMENT_NOT_FOUND",
  DELHIVERY_AUTH_FAILED       = "DELHIVERY_AUTH_FAILED",
  DELHIVERY_ORDER_FAILED      = "DELHIVERY_ORDER_FAILED",
  PINCODE_NOT_SERVICEABLE     = "PINCODE_NOT_SERVICEABLE",

  // Partial payment — balance leg
  /** The balance was already collected, by any channel. */
  BALANCE_ALREADY_SETTLED     = "BALANCE_ALREADY_SETTLED",
  /** The parcel has been manifested COD; the online link is closed by design. */
  BALANCE_LINK_DISPATCHED     = "BALANCE_LINK_DISPATCHED",
  /** Unknown or rotated balance token. */
  BALANCE_LINK_INVALID        = "BALANCE_LINK_INVALID",
  /** No outstanding balance on this order. */
  BALANCE_NOT_DUE             = "BALANCE_NOT_DUE",

  // Generic
  UNAUTHORIZED_ACCESS         = "UNAUTHORIZED_ACCESS",
  CONCURRENCY_CONFLICT        = "CONCURRENCY_CONFLICT",
}
