export enum PreOrderErrorCode {
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PREORDER_NOT_ENABLED = "PREORDER_NOT_ENABLED",
  PRODUCT_AVAILABLE = "PRODUCT_AVAILABLE", // in stock — buy normally instead of pre-ordering
  PREORDER_FULL = "PREORDER_FULL",
  BOOKING_EXCEEDS_TOTAL = "BOOKING_EXCEEDS_TOTAL",
  VARIANT_INVALID = "VARIANT_INVALID",
  INVALID_ADDRESS = "INVALID_ADDRESS",
  PREORDER_NOT_FOUND = "PREORDER_NOT_FOUND",
  UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
  INVALID_SIGNATURE = "INVALID_SIGNATURE",
  RAZORPAY_ORDER_ID_MISMATCH = "RAZORPAY_ORDER_ID_MISMATCH",
  AMOUNT_MISMATCH = "AMOUNT_MISMATCH",
  RAZORPAY_ORDER_CREATE_FAILED = "RAZORPAY_ORDER_CREATE_FAILED",
  INVALID_STATE = "INVALID_STATE",
  LINK_EXPIRED = "LINK_EXPIRED",
  OUT_OF_STOCK_AGAIN = "OUT_OF_STOCK_AGAIN",
  CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT",
}
